server:
  port: 6006
  maxHttpHeaderSize: 10240000
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    basedir:
      /usr/local/joyzone/business
    accesslog:
      enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 300MB
  application:
    name: joyzone-business
  security:
    user:
      name: joyzone
      password: Joyzone
  swagger:
     enable: true
  redis:
     host: 127.0.0.1
     port: 6379
     timeout: 20000
     pool:
       max-active: 8
       min-adle: 0
       max-idle: 8
       max-wait: -1
mybatis:
  type-aliases-package:  com.joyzone.platform.core.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/**.xml
mapper:
  mappers:
    - com.joyzone.platform.core.base.BaseMapper
  not-empty: true
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count:countSql
druid:
  url: jdbc:mysql://120.78.156.35:3306/joyzone?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: Joyzone@hgz
  initialSize: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true
logging:
  config: classpath:logback.xml
using:
  spring:
    schedulerFactory: false
secretId: AKIDDJF0rh6KckRDjCnpyeeVBkYQNGMIDg9J
secretKey:  1IRmyGn3FWlvukPSXKAQFy3vgF05rUwk
bucket:  joyzone-1257127706
fileSize: 2048000
scale: 0.8